### ISSUE TITLE
Update Portal Aus contact details

### ISSUE THREAD

**Issue by helenmountain** [tes/app-house-points#22]

**Comment by helenmountain** [comment]
AU portals are showing incorrect contact information for help and assistance. CServices, Australia are moving their queries into Freshdesk on the 18th June. 

Changes required: 

- from +44 203 194 3050 to 1800 734 758
- from recruitment@tesglobal.com to Customer.SupportAU@tes.com
![image.png](https://images.zenhubusercontent.com/60accb9986f9223f0ec8ad8a/520ec870-16d0-4a0e-9465-1f35e96388be)
URL needed

- from 07 3112 8568 to 1800 734 758
- from customersupport@smartteachers.com.au to Customer.SupportAU@tes.com
![image.png](https://images.zenhubusercontent.com/60accb9986f9223f0ec8ad8a/8b330731-b5bd-4030-b0b3-6d01a47b4de0)
URL needed

**Comment by applicity** [comment]
Issue moved to [tes/app-school-portal #198](https://github.com/tes/app-school-portal/issues/198) via [**ZenHub**](https://www.zenhub.com/)
