### ISSUE TITLE
School Points: Securely seed staff data

### ISSUE THREAD

**Issue by heatherstock** [tes/app-house-points#3]
### Why
3rd party applications will have their own database of schools and staff. We will need to associate the 3rd party schools with Tes schools and third party staff with Tes staff.

### Acceptance Criteria
- [ ] Securely associate the the school-points schools (Z1, Z2 and Z3) with real users from the equivalent Tes Schools
- [ ] User details are not checked into source control, or stored anywhere else that is publicly accessible

### Guidance
* We need to find a way of securely getting ZH20 user details into school-points. We might need to store the data in a DB (e.g. S3) and load on startup, or maybe we can inject the data via Elastic Beanstalk.

**Comment by cressie176** [comment]
Decided not to do this, and rely purely on the users from tes.com. Reasons are...

1. It keeps the demo simpler, and therefore easy to follow
1. There's no one right way to integrate users, so we might as well chose the simplest
