### ISSUE TITLE
School Points: Prepare an external (i.e. non Tes) live environment

### ISSUE THREAD

**Issue by cressie176** [tes/app-house-points#7]
### Why
* The purpose of this application is to provide a blueprint for 3rd party product vendors which includes things like tracking and analytics. If we deploy to the Tes environment, we will not have to deal with [CORS](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS) or routing related issues that the 3rd party vendors will face.

### Acceptance Criteria
The application is:
- [x] deployed to an environment completely isolated from the rest of tes.com
- [x] accessible from the common tes domains, e.g. tes.com, tesglobal.com, etc
- [x] accessible over HTTPS
- [x] accessible via a friendly url, e.g. https://school-points.tes-demos.com

### Guidance
* @john-nuttall may be able to suggest a spare domain we can use, assist with in the creation of an isolated environment (he suggested setting up a new AWS account via [Terraform](https://www.terraform.io/)) and with the SSL certificate

**Comment by cressie176** [comment]
We've deployed to Heroku, but using my personal rather than Tes account temporarily. So keeping open for now. See https://github.com/tes/infra/issues/2373

**Comment by cressie176** [comment]
This can be closed once we've shared the heroku account details

**Comment by john-nuttall** [comment]
@cressie176 are they added to 1password ?

**Comment by hustler** [comment]
@john-nuttall I have the Tes Global 1password setup. What vault do I need access to in order to now manage this apps secrets?

**Comment by john-nuttall** [comment]
@hustler @bettiolo needs to add you to the Engineering shared vault

**Comment by hustler** [comment]
@john-nuttall ta
@bettiolo can you add me to the Engineering shared vault please.
